### ISSUE TITLE
Receiver cannot see video of creator

### ISSUE THREAD

**Issue by ArpitKotecha** [k161196/react-native-webrtc-video-call#1]
The person who created the room can see both his and other user video but the user who joined cannot see creator video

**Comment by onebot-collab** [comment]
Hi @ArpitKotecha , i'm facing the same issue. Can you tell me how you solved this kind of issue? thank you

**Comment by ArpitKotecha** [comment]
> Hi @ArpitKotecha , i'm facing the same issue. Can you tell me how you solved this kind of issue? thank you

Hi @onebot-collab, I didn't, our requirement got changed last moment and we proceeded with Twilio.
